app = "acrobot-rednafi"
primary_region = "ams"

[build]

# Virtual machine configuration
[[vm]]
  size = "shared-cpu-1x"   # VM size with sufficient resources
  processes = ["app"]
  memory_mb = 512          # Set custom memory size (512MB)
  ignore_app_secrets = false

# Inject runtime environment variables
[env]
  PYTHONUNBUFFERED = "1"  # Ensure Python logs appear instantly
